services:
  postgres:
    image: postgres:17
    container_name: fluxchat_local_db

    environment:
      POSTGRES_USER: fluxchat_admin
      POSTGRES_PASSWORD: password321
      POSTGRES_DB: fluxchat

    ports:
      - "5432:5432"

    volumes:
      - fluxchat_data:/var/lib/postgresql/data

volumes:
  fluxchat_data: